coordinator/config/routes.rb
Coordinator::Application.routes.draw do
  resources :seccions

  resources :carpeta

  resources :maestria

  resources :pensums

  resources :materia

  root :to => 'home#index'

end

coordinator/app/controllers/materia_controller.rb
class MateriaController < ApplicationController
  # GET /materia
  # GET /materia.json
  def index
    @materia = Materium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @materia }
    end
  end

  # GET /materia/1
  # GET /materia/1.json
  def show
    @materium = Materium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @materium }
    end
  end

  # GET /materia/new
  # GET /materia/new.json
  def new
    @materium = Materium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @materium }
    end
  end

  # GET /materia/1/edit
  def edit
    @materium = Materium.find(params[:id])
  end

  # POST /materia
  # POST /materia.json
  def create
    @materium = Materium.new(params[:materium])

    respond_to do |format|
      if @materium.save
        format.html { redirect_to @materium, notice: 'Materium was successfully created.' }
        format.json { render json: @materium, status: :created, location: @materium }
      else
        format.html { render action: "new" }
        format.json { render json: @materium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /materia/1
  # PUT /materia/1.json
  def update
    @materium = Materium.find(params[:id])

    respond_to do |format|
      if @materium.update_attributes(params[:materium])
        format.html { redirect_to @materium, notice: 'Materium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @materium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materia/1
  # DELETE /materia/1.json
  def destroy
    @materium = Materium.find(params[:id])
    @materium.destroy

    respond_to do |format|
      format.html { redirect_to materia_url }
      format.json { head :no_content }
    end
  end
end

coordinator/app/helpers/materia_helper.rb
module MateriaHelper
end

coordinator/app/views/materia/_form.html.erb
<%= form_for(@materium) do |f| %>
  <% if @materium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@materium.errors.count, "error") %> prohibited this materium from being saved:</h2>

      <ul>
      <% @materium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

coordinator/app/views/materia/edit.html.erb
<h1>Editing materium</h1>

<%= render 'form' %>

<%= link_to 'Show', @materium %> |
<%= link_to 'Back', materia_path %>

coordinator/app/views/materia/index.html.erb
<h1>Materias</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Codigo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @materia.each do |materium| %>
  <tr>
    <td><%= materium.nombre %></td>
    <td><%= materium.codigo %></td>
    <td><%= link_to 'Mostrar', materium %></td>
    <td><%= link_to 'Editar', edit_materium_path(materium) %></td>
    <td><%= link_to 'Eliminar', materium, method: :delete, data: { confirm: 'Esta seguro que desea eliminar esta materia?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Materia', new_materium_path %>

coordinator/app/views/materia/new.html.erb
<h1>New materium</h1>

<%= render 'form' %>

<%= link_to 'Back', materia_path %>

coordinator/app/views/materia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @materium.nombre %>
</p>

<p>
  <b>Codigo:</b>
  <%= @materium.codigo %>
</p>


<%= link_to 'Edit', edit_materium_path(@materium) %> |
<%= link_to 'Back', materia_path %>