coordinator/config/routes.rb
Coordinator::Application.routes.draw do
  resources :seccions

  resources :carpeta

  resources :maestria

  resources :pensums

  resources :materia

  root :to => 'home#index'

end

coordinator/app/models/seccion.rb
class Seccion < ActiveRecord::Base
  attr_accessible :creditos, :numero, :profesor

  #Validar todos los campos requeridos
  validates :creditos, :numero, :profesor => {true,
  	:message => "Todos los campos son requeridos"}
  
  #Validar tamaño y tipos
  validates :creditos, :numericality => { :only_integer => true }
  validates :numero, :numericality => { :only_integer => true }
  validates :numero, :numericality => { :greater_than_or_equal_to => 0 }

end

coordinator/app/controllers/seccions_controller.rb
class SeccionsController < ApplicationController
  # GET /seccions
  # GET /seccions.json
  def index
    @seccions = Seccion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seccions }
    end
  end

  # GET /seccions/1
  # GET /seccions/1.json
  def show
    @seccion = Seccion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seccion }
    end
  end

  # GET /seccions/new
  # GET /seccions/new.json
  def new
    @seccion = Seccion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seccion }
    end
  end

  # GET /seccions/1/edit
  def edit
    @seccion = Seccion.find(params[:id])
  end

  # POST /seccions
  # POST /seccions.json
  def create
    @seccion = Seccion.new(params[:seccion])

    respond_to do |format|
      if @seccion.save
        format.html { redirect_to @seccion, notice: 'Seccion was successfully created.' }
        format.json { render json: @seccion, status: :created, location: @seccion }
      else
        format.html { render action: "new" }
        format.json { render json: @seccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seccions/1
  # PUT /seccions/1.json
  def update
    @seccion = Seccion.find(params[:id])

    respond_to do |format|
      if @seccion.update_attributes(params[:seccion])
        format.html { redirect_to @seccion, notice: 'Seccion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @seccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seccions/1
  # DELETE /seccions/1.json
  def destroy
    @seccion = Seccion.find(params[:id])
    @seccion.destroy

    respond_to do |format|
      format.html { redirect_to seccions_url }
      format.json { head :no_content }
    end
  end
end

coordinator/app/helpers/seccions_helper.rb
module SeccionsHelper
end

coordinator/app/views/seccions/_form.html.erb
<%= form_for(@seccion) do |f| %>
  <% if @seccion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seccion.errors.count, "error") %> prohibited this seccion from being saved:</h2>

      <ul>
      <% @seccion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br />
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :creditos %><br />
    <%= f.number_field :creditos %>
  </div>
  <div class="field">
    <%= f.label :profesor %><br />
    <%= f.text_field :profesor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

coordinator/app/views/seccions/edit.html.erb
<h1>Editing seccion</h1>

<%= render 'form' %>

<%= link_to 'Show', @seccion %> |
<%= link_to 'Back', seccions_path %>

coordinator/app/views/seccions/index.html.erb
<h1>Listado secciones!</h1>

<table>
  <tr>
    <th>Numero</th>
    <th>Creditos</th>
    <th>Profesor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seccions.each do |seccion| %>
  <tr>
    <td><%= seccion.numero %></td>
    <td><%= seccion.creditos %></td>
    <td><%= seccion.profesor %></td>
    <td><%= link_to 'Mostrar', seccion %></td>
    <td><%= link_to 'Editar', edit_seccion_path(seccion) %></td>
    <td><%= link_to 'Eliminar', seccion, method: :delete, data: { confirm: 'está seguro que desea eliminar esta seccion?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Seccion', new_seccion_path %>

coordinator/app/views/seccions/new.html.erb
<h1>New seccion</h1>

<%= render 'form' %>

<%= link_to 'Back', seccions_path %>

coordinator/app/views/seccions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Numero:</b>
  <%= @seccion.numero %>
</p>

<p>
  <b>Creditos:</b>
  <%= @seccion.creditos %>
</p>

<p>
  <b>Profesor:</b>
  <%= @seccion.profesor %>
</p>


<%= link_to 'Edit', edit_seccion_path(@seccion) %> |
<%= link_to 'Back', seccions_path %>