coordinator/config/routes.rb
Coordinator::Application.routes.draw do
  resources :seccions

  resources :carpeta

  resources :maestria

  resources :pensums

  resources :materia

  root :to => 'home#index'

end

coordinator/app/models/pensum.rb
class Pensum < ActiveRecord::Base
  attr_accessible :ano, :semestre
  has_many :materium
  belongs_to :maestrium

  #Validar todos los campos requeridos
  validates :ano, :semestre, :presence => {true,
  	:message => "Todos los campos son requeridos"}
  
  #Validar asociaciones -> No validar del otro lado (eg de materium a carpetum)
  validates_associated :materium
  
  #Validar tamaño y tipos
  validates :ano, :length => { :is => 4 }
  validates :ano, :numericality => { :only_integer => true }
  validates :ano, :numericality => { :greater_than => 1970 }
  validates :semestre, :length => { :is => 1 }
  validates :semestre, :numericality => { :only_integer => true }
  validates :semestre, :numericality => { :greater_than_or_equal_to => 0 }
  validates :semestre, :numericality => { :less_than_or_equal_to => 2 }

end

coordinator/app/controllers/pensums_controller.rb
class PensumsController < ApplicationController
  # GET /pensums
  # GET /pensums.json
  def index
    @pensums = Pensum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pensums }
    end
  end

  # GET /pensums/1
  # GET /pensums/1.json
  def show
    @pensum = Pensum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pensum }
    end
  end

  # GET /pensums/new
  # GET /pensums/new.json
  def new
    @pensum = Pensum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pensum }
    end
  end

  # GET /pensums/1/edit
  def edit
    @pensum = Pensum.find(params[:id])
  end

  # POST /pensums
  # POST /pensums.json
  def create
    @pensum = Pensum.new(params[:pensum])

    respond_to do |format|
      if @pensum.save
        format.html { redirect_to @pensum, notice: 'Pensum was successfully created.' }
        format.json { render json: @pensum, status: :created, location: @pensum }
      else
        format.html { render action: "new" }
        format.json { render json: @pensum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pensums/1
  # PUT /pensums/1.json
  def update
    @pensum = Pensum.find(params[:id])

    respond_to do |format|
      if @pensum.update_attributes(params[:pensum])
        format.html { redirect_to @pensum, notice: 'Pensum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pensum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pensums/1
  # DELETE /pensums/1.json
  def destroy
    @pensum = Pensum.find(params[:id])
    @pensum.destroy

    respond_to do |format|
      format.html { redirect_to pensums_url }
      format.json { head :no_content }
    end
  end
end

coordinator/app/helpers/pensums_helper.rb
module PensumsHelper
end

coordinator/app/views/pensums/_form.html.erb
<%= form_for(@pensum) do |f| %>
  <% if @pensum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pensum.errors.count, "error") %> prohibited this pensum from being saved:</h2>

      <ul>
      <% @pensum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ano %><br />
    <%= f.number_field :ano %>
  </div>
  <div class="field">
    <%= f.label :semestre %><br />
    <%= f.number_field :semestre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

coordinator/app/views/pensums/edit.html.erb
<h1>Editing pensum</h1>

<%= render 'form' %>

<%= link_to 'Show', @pensum %> |
<%= link_to 'Back', pensums_path %>

coordinator/app/views/pensums/index.html.erb
<h1>Pensums</h1>

<table>
  <tr>
    <th>Ano</th>
    <th>Semestre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pensums.each do |pensum| %>
  <tr>
    <td><%= pensum.ano %></td>
    <td><%= pensum.semestre %></td>
    <td><%= link_to 'Mostrar', pensum %></td>
    <td><%= link_to 'Editar', edit_pensum_path(pensum) %></td>
    <td><%= link_to 'Eliminar', pensum, method: :delete, data: { confirm: 'Esta seguro que desea eliminar este pensum?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Pensum', new_pensum_path %>

coordinator/app/views/pensums/new.html.erb
<h1>New pensum</h1>

<%= render 'form' %>

<%= link_to 'Back', pensums_path %>

coordinator/app/views/pensums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ano:</b>
  <%= @pensum.ano %>
</p>

<p>
  <b>Semestre:</b>
  <%= @pensum.semestre %>
</p>


<%= link_to 'Edit', edit_pensum_path(@pensum) %> |
<%= link_to 'Back', pensums_path %>