coordinator/config/routes.rb
Coordinator::Application.routes.draw do
  resources :seccions

  resources :carpeta

  resources :maestria

  resources :pensums

  resources :materia

  root :to => 'home#index'

end

coordinator/app/controllers/maestria_controller.rb
class MaestriaController < ApplicationController
  # GET /maestria
  # GET /maestria.json
  def index
    @maestria = Maestrium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @maestria }
    end
  end

  # GET /maestria/1
  # GET /maestria/1.json
  def show
    @maestrium = Maestrium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @maestrium }
    end
  end

  # GET /maestria/new
  # GET /maestria/new.json
  def new
    @maestrium = Maestrium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @maestrium }
    end
  end

  # GET /maestria/1/edit
  def edit
    @maestrium = Maestrium.find(params[:id])
  end

  # POST /maestria
  # POST /maestria.json
  def create
    @maestrium = Maestrium.new(params[:maestrium])

    respond_to do |format|
      if @maestrium.save
        format.html { redirect_to @maestrium, notice: 'Maestrium was successfully created.' }
        format.json { render json: @maestrium, status: :created, location: @maestrium }
      else
        format.html { render action: "new" }
        format.json { render json: @maestrium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /maestria/1
  # PUT /maestria/1.json
  def update
    @maestrium = Maestrium.find(params[:id])

    respond_to do |format|
      if @maestrium.update_attributes(params[:maestrium])
        format.html { redirect_to @maestrium, notice: 'Maestrium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @maestrium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maestria/1
  # DELETE /maestria/1.json
  def destroy
    @maestrium = Maestrium.find(params[:id])
    @maestrium.destroy

    respond_to do |format|
      format.html { redirect_to maestria_url }
      format.json { head :no_content }
    end
  end
end

coordinator/app/helpers/maestria_helper.rb
module MaestriaHelper
end

coordinator/app/views/maestria/_form.html.erb
<%= form_for(@maestrium) do |f| %>
  <% if @maestrium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maestrium.errors.count, "error") %> prohibited this maestrium from being saved:</h2>

      <ul>
      <% @maestrium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

coordinator/app/views/maestria/edit.html.erb
<h1>Editing maestrium</h1>

<%= render 'form' %>

<%= link_to 'Show', @maestrium %> |
<%= link_to 'Back', maestria_path %>

coordinator/app/views/maestria/index.html.erb
<h1>Maestrias</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @maestria.each do |maestrium| %>
  <tr>
    <td><%= maestrium.codigo %></td>
    <td><%= link_to 'Mostrar', maestrium %></td>
    <td><%= link_to 'Editar', edit_maestrium_path(maestrium) %></td>
    <td><%= link_to 'Eliminar', maestrium, method: :delete, data: { confirm: 'Esta seguro que quiere eliminar esta maestria?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Maestria', new_maestrium_path %>

coordinator/app/views/maestria/new.html.erb
<h1>New maestrium</h1>

<%= render 'form' %>

<%= link_to 'Back', maestria_path %>

coordinator/app/views/maestria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @maestrium.codigo %>
</p>


<%= link_to 'Edit', edit_maestrium_path(@maestrium) %> |
<%= link_to 'Back', maestria_path %>